---
parent: "api_v1_system-settings"
name: "api_v1_system-settings_get_query_param_invalid_data_type_for_int_page"
description: null
type: "SUITE"
endpoint: "/api/v1/system-settings?page=JTQRdz"
method: "GET"
auth: "BASIC"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode != 200"
tags:
- "V1"
authors:
- "FX Bot"
inactive: false
