---
parent: "api_v1_system-settings"
name: "api_v1_system-settings_post_create_abstract"
description: null
type: "ABSTRACT"
endpoint: "/api/v1/system-settings"
method: "POST"
auth: ""
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases:
- id: 1
  body: "{\"inactive\":null,\"key\":null,\"label\":null,\"value\":null}"
  inactive: false
assertions:
- "@StatusCode == 200"
tags:
- "V1"
authors:
- "FX Bot"
inactive: false
