---
parent: "api_v1_system-settings_id"
name: "api_v1_system-settings_id_delete_delete_abstract"
description: null
type: "ABSTRACT"
endpoint: "/api/v1/system-settings/{{@api_v1_system-settings_post_create_abstract_Response.id}}"
method: "DELETE"
auth: ""
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode == 200"
tags:
- "V1"
authors:
- "FX Bot"
inactive: false
