---
parent: "api_v1_system-settings_batch"
name: "api_v1_system-settings_batch_post_auth_invalid"
description: null
type: "SUITE"
endpoint: "/api/v1/system-settings/batch"
method: "POST"
auth: "INVALID_AUTH"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode == 401"
tags:
- "V1"
authors:
- "FX Bot"
inactive: false
